/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-17-2013
 * 
 * XDoclet definition:
 * @struts.form name="userFormForm"
 */
public class SelectModelInfoForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/*
	 * Generated Methods
	 */

	private String modelName;

	

	public String getModelName() {
		return modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset() {
		modelName="";

	}

	

	
}