/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-17-2013
 * 
 * XDoclet definition:
 * @struts.form name="userFormForm"
 */
public class SelectCustRecordForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/*
	 * Generated Methods
	 */
	private String contactid;
	private String custid;
	private String contact;
	private String contacttime;
	private String deleteflag;
	private String custname;
	private String phonenumber1;
	private String custcreatefrom;
	private String custcreateto;

	

	public String getCustname() {
		return custname;
	}

	public void setCustname(String custname) {
		this.custname = custname;
	}

	public String getPhonenumber1() {
		return phonenumber1;
	}

	public void setPhonenumber1(String phonenumber1) {
		this.phonenumber1 = phonenumber1;
	}

	public String getCustcreatefrom() {
		return custcreatefrom;
	}

	public void setCustcreatefrom(String custcreatefrom) {
		this.custcreatefrom = custcreatefrom;
	}

	public String getCustcreateto() {
		return custcreateto;
	}

	public void setCustcreateto(String custcreateto) {
		this.custcreateto = custcreateto;
	}

	public String getContactid() {
		return contactid;
	}

	public void setContactid(String contactid) {
		this.contactid = contactid;
	}

	public String getCustid() {
		return custid;
	}

	public void setCustid(String custid) {
		this.custid = custid;
	}

	public String getContact() {
		return contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getContacttime() {
		return contacttime;
	}

	public void setContacttime(String contacttime) {
		this.contacttime = contacttime;
	}

	public String getDeleteflag() {
		return deleteflag;
	}

	public void setDeleteflag(String deleteflag) {
		this.deleteflag = deleteflag;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset() {
		contactid="";
		custid="";
		contact="";
		contacttime="";
		deleteflag="";
	}

	

	
}