/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.context.ApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;

import com.struts.form.UserFormForm;
import com.user.model.User;
import com.user.service.UserManager;
import com.user.service.imp.UserManagerImpl;

/** 
 * MyEclipse Struts
 * Creation date: 08-17-2013
 * 
 * XDoclet definition:
 * @struts.action path="/userForm" name="userFormForm" input="/User/userForm.jsp" scope="request" validate="true"
 */
public class UserFormAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	protected static ApplicationContext ctx = null;

	/**
	 * @param name
	 * @return java.lang.Object
	 */
	protected Object getBean(String name) {
		if (ctx == null) {
			ctx = WebApplicationContextUtils
					.getRequiredWebApplicationContext(servlet
							.getServletContext());
		}
		return ctx.getBean(name);
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward userLogin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String s="1";
		try {
			UserManager userManager = (UserManager) this
			.getBean("userManager");
			
			UserFormForm userForm = (UserFormForm) form;// TODO Auto-generated method stub
		    User user=new User();
		    user.setUsername(userForm.getUsername());
		    user.setUserpassword(userForm.getUserpassword());
			boolean b = userManager.selectUser(user);
			
			if(b==true){
				s="2";
				request.setAttribute("s", s);
				return mapping.findForward("success");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return mapping.findForward("error");
		}
		request.setAttribute("s", s);
		return mapping.findForward("error");	
	}
}